### ISSUE TITLE
eror again bro

### ISSUE THREAD

**Issue by RidhoNGPX** [ajmeese7/spambot#73] opened 2023-01-18 01:05 UTC
![Screenshot_20230118-080355_Termux](https://user-images.githubusercontent.com/89362181/213055433-12685088-f2a9-4811-9192-9c1ab6bbf879.png)

**Comment by ridx807** [comment] 2023-01-18 10:51
> ![Screenshot_20230118-080355_Termux](https://user-images.githubusercontent.com/89362181/213055433-12685088-f2a9-4811-9192-9c1ab6bbf879.png)

Solved by delete node_modules and installing fresh discord.js
```npm install discord.js```

**Comment by ridx807** [comment] 2023-01-18 11:12
Sama bro, solved belum?

**Comment by ajmeese7** [comment] 2023-01-21 19:59
Closing as duplicate of #74, even though this one was made first that one has text instead of an image.

**Closed as not planned by ajmeese7** 2023-01-21 19:59 UTC
